### ISSUE TITLE
你好，我就是看你不顺眼

### ISSUE THREAD

**Issue by zhangcheng1164** [zh1165/git_learning#1]
**Describe the bug**
没有啥bug，我就是看你不顺眼

**To Reproduce**
1. 看你不顺眼
2. 看你不顺眼

**Expected behavior**
希望能看你顺眼一些

**Comment by zhangcheng1164** [comment]
@zh1165 我真的是看你不顺眼，没骗你

**Comment by zh1165** [comment]
USB
